---
- name: Create RG
  hosts: localhost
  connection: local
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: WeEu-Pla-Prd-Rsg-01
      location: westeurope
      tags:
          testing: testing
          delete: never
