---
- name: Create RG
  hosts: localhost
  connection: local
  vars_files:
    - ./AnsTest2/vars/vars.yml
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ az_resource_group_name }}"
      location: westeurope
      tags:
          testing: testing
          delete: never
