---
- name: Create subnet
  hosts: localhost
  connection: local
  tasks:
  - name: Create a subnet
    azure_rm_subnet:
      name: WeEU-Pla-Prd-Vnet-Snet-02
      virtual_network_name: WeEU-Pla-Prd-Vnet-02
      resource_group: WeEu-Pla-Prd-Rsg-01
      address_prefix_cidr: '10.22.1.0/24'
